=== susmitha-ann/PeopleCareDP/updatedHealthDbAndSchema/health_data_base.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- ContactType Definition -->
	<xs:complexType name="ContactType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="1"/>
			<xs:element name="Email" type="xs:string" minOccurs="0"/>
			<xs:element name="address" type="xs:string" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<!-- typeOfSeekerType Definition -->
	<xs:complexType name="typeOfSeekerType">
		<xs:choice>
			<xs:element name="Elderly" minOccurs="0" type="xs:string" nillable="true"/>
			<xs:element name="Handicap">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="HandicapLevel" type="xs:string" default="High"/>
							<!-- High , Medium , Low -->
							<xs:attribute name="durationOfHandicap" type="xs:string" default="chronic"/>
							<!-- chronic or acute -->
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="postPartum" type="xs:string"/>
		</xs:choice>
	</xs:complexType>
	<!-- ProvidersType Definition-->
	<xs:complexType name="ProvidersType">
		<xs:choice>
			<xs:element name="ServiceCompanies" type="CompaniesType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="aloneProviders" type="AloneType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<!--CompaniesType Definition-->
	<xs:complexType name="CompaniesType">
		<xs:sequence>
			<xs:element name="companieID" type="xs:string"/>
			<!-- a key ref would be created here-->
			<xs:element name="CompanieInfos" type="ContactType"/>
		</xs:sequence>
	</xs:complexType>
	<!--AloneType Definition-->
	<xs:complexType name="AloneType">
		<xs:sequence>
			<xs:element name="PhoneNumber" type="xs:integer"/>
			<xs:element name="gender">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Male"/>
						<xs:enumeration value="Female"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--ServiceType Definition-->
	<xs:complexType name="ServiceType">
		<xs:sequence>
			<xs:element name="ServiceInfos" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ServiceID" type="xs:string"/>
						<xs:element name="ProviderID" type="xs:string"/>
						<!--here i had issues with the db validation so i reconstructed the service type to match the db-->
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="SCHEDULING" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="occurrence" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Also here i had to redefine the ActivityType to encapsulate every details of the activities otherwise the db won't be valid against the schema -->
	<xs:complexType name="ActivityType">
		<xs:sequence>
			<xs:element name="ActivityInfo" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ActivityID" type="xs:string"/>
						<xs:element name="ProviderID" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="SCHEDULING" type="xs:date"/>
			<xs:element name="Duration" type="xs:duration"/>
			<!--outpout: PnYnMnDTnHnMnS :P:period,year,month,day,hours,minutes,seconds-->
		</xs:sequence>
		<xs:attribute name="occurrence" type="xs:string" use="required"/>
	</xs:complexType>
	<!--ManagementSystem Element Definition-->
	<xs:element name="ManagementSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Users" type="UsersType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<!--Defining the Keys -->
		<xs:key name="userKey">
			<xs:selector xpath="Users/AssistanceSeeker"/>
			<xs:field xpath="SeekerID"/>
		</xs:key>
		<xs:key name="providerKey">
			<xs:selector xpath="Users/HealthProviders"/>
			<xs:field xpath="ProviderID"/>
		</xs:key>
		<xs:key name="serviceKey">
			<xs:selector xpath="Services/*/ServiceInfos"/>
			<xs:field xpath="ServiceID"/>
		</xs:key>
		<xs:key name="activityKey">
			<xs:selector xpath="Activities/*/ActivityInfo"/>
			<!--had to put the /*/ to match every activityID : done with chatgpt-->
			<xs:field xpath="ActivityID"/>
		</xs:key>
		<!--Defining the Keyrefs-->
		<!--Here i used chatgpt to correct where i put keyrefs, i had some errors at first but corrected them later -->
		<xs:keyref name="SeekerRef" refer="userKey">
			<xs:selector xpath="UserParticipation/entry"/>
			<xs:field xpath="SeekerID"/>
		</xs:keyref>
		<xs:keyref name="ProviderRef" refer="providerKey">
			<xs:selector xpath="UserParticipation/entry"/>
			<xs:field xpath="ProviderID"/>
		</xs:keyref>
		<xs:keyref name="ServiceRef" refer="serviceKey">
			<xs:selector xpath="UserParticipation/entry/ParticipationDateForServices"/>
			<xs:field xpath="@ServiceID"/>
		</xs:keyref>
		<xs:keyref name="ActivityRef" refer="activityKey">
			<xs:selector xpath="UserParticipation/entry"/>
			<xs:field xpath="ActivityID"/>
		</xs:keyref>
		<xs:keyref name="ActivityProviderRef" refer="providerKey">
			<xs:selector xpath="UserParticipation/entry"/>
			<xs:field xpath="ActivityProviderID"/>
		</xs:keyref>
		<xs:keyref name="ServiceProviderRef" refer="providerKey">
			<xs:selector xpath="UserParticipation/entry/ServiceProviderID"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<!-- Defining UsersType-->
	<xs:complexType name="UsersType">
			<xs:sequence>
				<xs:element name="AssistanceSeeker" type="AssistanceSeekerType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	<!-- Defining AssistanceSeekerType-->
	<xs:complexType name="AssistanceSeekerType">
    <xs:sequence>
        <xs:element name="SeekerID" type="xs:string"/>
        <xs:element name="contactInfos" type="ContactType"/>
        <xs:element name="age">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="xs:int">
                        <xs:attribute name="ageUnit" type="xs:string" default="Years"/>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
        <xs:element name="gender">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Male"/>
                    <xs:enumeration value="Female"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="typeOfSeeker" type="typeOfSeekerType"/>
        <xs:element name="HealthProviders" type="HealthProvidersType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="Services" type="ServicesType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="Activities" type="ActivitiesType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="UserParticipation" type="UserParticipationType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

	<!-- Defining HealthProvidersType-->
<xs:complexType name="HealthProvidersType">
    <xs:sequence>
        <xs:element name="ProviderID" type="xs:string"/>
        <xs:element name="providerInfos" type="ContactType"/>
        <xs:element name="TypeOfHealthProviders" type="ProvidersType"/>
    </xs:sequence>
</xs:complexType>

<!-- Defining ServicesType-->
	<xs:complexType name="ServicesType">
			<xs:choice maxOccurs="unbounded">   <!-- i had to change sequence to choice to allow multiple elements to appear in any order-->
				<xs:element name="MedicalCare" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="HomeCare" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="HomeRehabilitation" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Postpartum-NeonatalCARE" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:complexType>
		<!-- Defining ActivitiesType-->
	<xs:complexType name="ActivitiesType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="ElderlyActivities" type="ActivityType" minOccurs="0"/>
				<xs:element name="WithHandicapActivities" type="ActivityType" minOccurs="0"/>
				<xs:element name="RehabActivities" type="ActivityType" minOccurs="0"/>
				<xs:element name="PostnatalAcitvities" type="ActivityType" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<!--UserParticipationType Definition-->
	<xs:complexType name="UserParticipationType">
		<xs:sequence>
			<xs:element name="entry" maxOccurs="unbounded">
				<xs:complexType>
					<xs:choice maxOccurs="unbounded">
						<xs:element name="ServiceProviderID" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="ActivityProviderID" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="SeekerID" type="xs:string" minOccurs="1"/>
						<xs:element name="ActivityID" type="xs:string" minOccurs="0"/>
						<xs:element name="ParticipationDateForActivities" type="xs:date" minOccurs="1" maxOccurs="unbounded"/>
						<!-- Correcting ParticipationDateForServices -->
						<xs:element name="ParticipationDateForServices" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:date">
										<xs:attribute name="ServiceID" type="xs:string" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== susmitha-ann/PeopleCareDP/updatedHealthDbAndSchema/HealthDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>
<ManagementSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="health_data_base.xsd">
	<Users>
		<AssistanceSeeker>
			<SeekerID>AS589</SeekerID>
			<contactInfos>
				<Name>William Smith</Name>
				<Email>willy221@gmail.com</Email>
				<address>31 Rose Street, Kingston, NY, 12401</address>
			</contactInfos>
			<age ageUnit="Years">65</age>
			<gender>Male</gender>
			<typeOfSeeker>
				<Elderly>Senior</Elderly>
			</typeOfSeeker>
		
		<HealthProviders>
			<ProviderID>HP784</ProviderID>
			<providerInfos>
				<Name>Catherine Martin</Name>
				<Email>catherine.Mt@agingCorp.com</Email>
				<address>10 Bowdoin Street, Boston, Massachusetts, 02108</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<!--i have to put in every companieType a companieID to much the schema-->
				<ServiceCompanies>
					<companieID>C512</companieID>
					<CompanieInfos>
						<Name>Aging Force Corporation</Name>
						<Email>AgingForce@agingCorp.com</Email>
						<address>12 Adams Street, Boston, Massachusetts, 02108</address>
					</CompanieInfos>
				</ServiceCompanies>
			</TypeOfHealthProviders>
		</HealthProviders>
		<HealthProviders>
			<ProviderID>HP795</ProviderID>
			<providerInfos>
				<Name>Alain Moore</Name>
				<Email>Alain.Mr@agingCorp.com</Email>
				<address>30 Aberdeen Street, Boston, Massachusetts, 02108</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<ServiceCompanies>
					<companieID>C512</companieID>
					<CompanieInfos>
						<Name>Aging Force Corporation</Name>
						<Email>AgingForce@agingCorp.com</Email>
						<address>12 Adams Street, Boston, Massachusetts, 02108</address>
					</CompanieInfos>
				</ServiceCompanies>
			</TypeOfHealthProviders>
		</HealthProviders>
		<HealthProviders>
			<ProviderID>HP320</ProviderID>
			<providerInfos>
				<Name>John Davis</Name>
				<Email>Johnny.Davis@agingCorp.com</Email>
				<address>30 Aberdeen Street, Boston, Massachusetts, 02108</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<ServiceCompanies>
					<companieID>C512</companieID>
					<CompanieInfos>
						<Name>Aging Force Corporation</Name>
						<Email>AgingForce@agingCorp.com</Email>
						<address>12 Adams Street, Boston, Massachusetts, 02108</address>
					</CompanieInfos>
				</ServiceCompanies>
			</TypeOfHealthProviders>
		</HealthProviders>
	
	<Services>
		<HomeCare occurrence="daily">
			<ServiceInfos>
				<ServiceID>S445</ServiceID>
				<ProviderID>HP784</ProviderID>
			</ServiceInfos>
			<Description>Home Nursing Care : daily living needs,toiletting,bathing,dressing, meal planning etc..</Description>
			<SCHEDULING>2024-02-03</SCHEDULING>
		</HomeCare>
		<MedicalCare occurrence="twice/week">
			<ServiceInfos>
				<ServiceID>S458</ServiceID>
				<ProviderID>HP795</ProviderID>
			</ServiceInfos>
			<Description> Medication administration,injections, monitoring of health conditions, and managing chronic diseases like diabetes,hypertension; Bowel diseases,neural diseases..</Description>
			<SCHEDULING>2024-02-03</SCHEDULING>
		</MedicalCare>
	</Services>
	<Activities>
		<ElderlyActivities occurrence="once/week">
			<ActivityInfo>
				<ActivityID>A111</ActivityID>
				<ProviderID>HP320</ProviderID>
			</ActivityInfo>
			<Description>Water Aerobics : easy exercises on the joint , helping also maintain the cardiovascular health and prevent sedentarity</Description>
			<SCHEDULING>2023-05-05</SCHEDULING>
			<Duration>PT1H45M</Duration>
		</ElderlyActivities>
	</Activities>
	<UserParticipation>
		<entry>
			<ServiceProviderID>HP784</ServiceProviderID>
			<ServiceProviderID>HP795</ServiceProviderID>
			<!--Here i had to change and differnciate activity and service provider ID otherwise the entry won't support multiple providers ID-->
			<ActivityProviderID>HP320</ActivityProviderID>
			<SeekerID>AS589</SeekerID>
			<ActivityID>A111</ActivityID>
			<ParticipationDateForActivities>2023-05-20</ParticipationDateForActivities>
			<ParticipationDateForServices ServiceID="S445">2023-02-06</ParticipationDateForServices>
			<ParticipationDateForServices ServiceID="S458">2024-02-06</ParticipationDateForServices>
		</entry>
	</UserParticipation>
	</AssistanceSeeker>
		<AssistanceSeeker>
			<SeekerID>AS398</SeekerID>
			<contactInfos>
				<Name>Margaret Wilson</Name>
				<Email/>
				<address>12 Peachtree Street, Atlanta, Georgia, 30033</address>
			</contactInfos>
			<age ageUnit="Years">55</age>
			<gender>Female</gender>
			<typeOfSeeker>
				<Handicap HandicapLevel="High" durationOfHandicap="chronic">Post-stroke sequelae</Handicap>
			</typeOfSeeker>
		
		<HealthProviders>
			<ProviderID>HP105</ProviderID>
			<providerInfos>
				<Name>Suzana Hernandez</Name>
				<Email>suzy.her@hotmail.com</Email>
				<address>10th Street NW , Atlanta, Georgia, 30318</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<aloneProviders>
					<PhoneNumber>0014044796005</PhoneNumber>
					<gender>Female</gender>
				</aloneProviders>
			</TypeOfHealthProviders>
		</HealthProviders>
		<HealthProviders>
			<ProviderID>HP222</ProviderID>
			<providerInfos>
				<Name>redBrainAssociation</Name>
				<Email>michaelZ.association@redBrain.org</Email>
				<address>5th Avenue RZ, Atlanta , Georgia, 30318</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<ServiceCompanies>
					<companieID>C0698</companieID>
					<CompanieInfos>
						<Name>RED BRAIN AND HEART co</Name>
						<Email>redBrain.service@redBrain.com</Email>
						<address>5th Avenue RZ, Atlanta ,Georgia, 30318</address>
					</CompanieInfos>
				</ServiceCompanies>
			</TypeOfHealthProviders>
		</HealthProviders>
	
	<Services>
		<MedicalCare occurrence="daily">
			<ServiceInfos>
				<ServiceID>S532</ServiceID>
				<ProviderID>HP105</ProviderID>
			</ServiceInfos>
			<Description>Rehabilitation Nursing, home personal care, health monitoring , Medication administration</Description>
			<SCHEDULING>2023-09-08</SCHEDULING>
		</MedicalCare>
	</Services>
	<Activities>
		<WithHandicapActivities occurrence="once/week">
			<ActivityInfo>
				<ActivityID>A897</ActivityID>
				<ProviderID>HP222</ProviderID>
			</ActivityInfo>
			<Description>Support Groups: Participation in stroke survivor support groups</Description>
			<SCHEDULING>2023-11-08</SCHEDULING>
			<Duration>PT2H45M</Duration>
		</WithHandicapActivities>
	</Activities>
	<UserParticipation>
		<entry>
			<ServiceProviderID>HP105</ServiceProviderID>
			<ActivityProviderID>HP222</ActivityProviderID>
			<SeekerID>AS398</SeekerID>
			<ActivityID>A897</ActivityID>
			<ParticipationDateForActivities>2023-11-22</ParticipationDateForActivities>
			<ParticipationDateForServices ServiceID="S532">2023-09-10</ParticipationDateForServices>
		</entry>
	</UserParticipation>
	</AssistanceSeeker>
	
		<AssistanceSeeker>
			<SeekerID>AS625</SeekerID>
			<contactInfos>
				<Name>James Brown</Name>
				<Email>Jamy.BY@gmail.com</Email>
				<address>4TH Avenue, Washington Street, NY, 12514</address>
			</contactInfos>
			<age ageUnit="Years">32</age>
			<gender>Male</gender>
			<typeOfSeeker>
				<Handicap HandicapLevel="Medium" durationOfHandicap="Acute">Residual Symptoms following a Road Accident</Handicap>
			</typeOfSeeker>
		
		<HealthProviders>
			<ProviderID>HP9144</ProviderID>
			<providerInfos>
				<Name>Adam Raley</Name>
				<Email>Adam.Raley@MyRehab.com</Email>
				<address>5th Avenue, Washington Street , NY, 12514</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<ServiceCompanies>
					<companieID>C5247</companieID>
					<CompanieInfos>
						<Name>MyRehab</Name>
						<Email>Custom.service@MyRehab.com</Email>
						<address>47th street, Chelsea , NY, 10011</address>
					</CompanieInfos>
				</ServiceCompanies>
			</TypeOfHealthProviders>
		</HealthProviders>
	
	<Services>
		<HomeRehabilitation occurrence="twice/week">
			<ServiceInfos>
				<ServiceID>S535</ServiceID>
				<ProviderID>HP9144</ProviderID>
			</ServiceInfos>
			<Description>Physical Therapy-Pain Management-Lifestyle Adjustement</Description>
			<SCHEDULING>2024-06-02</SCHEDULING>
			
		</HomeRehabilitation>
	</Services>
	<UserParticipation>
		<entry>
			<ServiceProviderID>HP9144</ServiceProviderID>
			<SeekerID>AS625</SeekerID>
			<ParticipationDateForServices ServiceID="S535">2024-07-15</ParticipationDateForServices>
		</entry>
	</UserParticipation>
	</AssistanceSeeker>
		<AssistanceSeeker>
			<SeekerID>AS780</SeekerID>
			<contactInfos>
				<Name>Sandra Noles James</Name>
				<Email>Sandra.Njames02@hotmail.com</Email>
				<address>Oak Avenue, Pasadena, CA, 91107</address>
			</contactInfos>
			<age ageUnit="Years">28 </age>
			<gender>Female</gender>
			<typeOfSeeker>
				<postPartum>Postpartum Doula Support and Help with Lactation</postPartum>
			</typeOfSeeker>
		
		<HealthProviders>
			<ProviderID>HP392</ProviderID>
			<providerInfos>
				<Name>Anna Dawson</Name>
				<Email>Anna.Dawson@NewGarden.com</Email>
				<address>Pearl Street, Pomona , CA, 91768</address>
			</providerInfos>
			<TypeOfHealthProviders>
				<ServiceCompanies>
					<companieID>c3620</companieID>
					<CompanieInfos>
						<Name>Baby NEW Garden</Name>
						<Email>Custom.service@NewGarden.com</Email>
						<address>8705 Front Street, Pacoima, CA, 91331</address>
					</CompanieInfos>
				</ServiceCompanies>
			</TypeOfHealthProviders>
		</HealthProviders>
		<HealthProviders>
			<ProviderID>HP354</ProviderID>
			<providerInfos>
				<Name>Patricia Gareth</Name>
				<Email>Patricia.GA@happyCare.com</Email>
				<address> Avis Road, Berkeley, CA, 94710 </address>
			</providerInfos>
			<TypeOfHealthProviders>
				<ServiceCompanies>
					<companieID>C741</companieID>
					<CompanieInfos>
